baseurl: https://otus.bruh.ltd
languageCode: en-us
theme: stack
paginate: 5
title: Otus9051's Tech Adventures

# Change it to your Disqus shortname before using

# GA Tracking ID
googleAnalytics: G-2QCPWHM5C0

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
        - Android
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2021
        customText: uwu

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        avatar:
            local: false
            src: https://avatars.githubusercontent.com/u/58171861?s=400&u=8941e822ac370b4b4984a1f5cf18650b6c5ebf61&v=4

    article:
        math: false
        license:
            enabled: true
            default: WTFPL 2.0

    comments:
        enabled: false
        provider: 

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
#menu:
#    main:
#        - identifier: home
#          name: Home
#          url: /
#          weight: -100
#          pre: home
#
#related:
#    includeNewer: true
#    threshold: 60
#    toLower: false
#    indices:
#        - name: tags
#          weight: 100
#
#        - name: categories
#          weight: 200
#
#markup:
#    highlight:
#        noClasses: false
